id = "canipls-lint"
name = "canipls"
version = "0.0.1"
schema_version = 1
authors = ["Taylor Plewe <tplewe@outlook.com>"]
description = "Get caniuse support info right in your editor"
repository = "https://github.com/taylorplewe/canipls-zed"

[language_servers.canipls]
name = "canipls"
languages = [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "TSX",
    "Vue.js",
    "Svelte",
    "Astro",
]
